version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres_cursos
    restart: always
    environment:
      POSTGRES_DB: cursos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring

  # MySQL
  mysql:
    image: mysql:8.0.33
    container_name: mysql_usuarios
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: usuarios_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring
  # Microservicio usuarios
  msvc-usuarios:
    image: usuarios:latest
    ports:
      - "8001:8001"
    networks:
      - spring
    depends_on:
      - mysql
    restart: always
  # Microservicio cursos
  msvc-cursos:
    image: cursos:latest
    ports:
      - "8002:8002"
    networks:
      - spring
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
  mysql_data:
networks:
  spring:



